development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis_url) %>
  channel_prefix: coffee_house_production
